### ISSUE TITLE
Using match to match possible selector values

### ISSUE THREAD

**Issue by Navmed** [lefthandedgoat/canopy#191]
This is due to minimal F# experience (I've been doing a lot of reading, but no real experience). On my page I want to test login and logout functionality. My (incomplete) code looks like this:
```
"Login and Logout" &&& fun _ ->
    url "http://localhost/mywebapp/default/index"

    match "#logged-in-user > a" with 
    | "Login" -> click "#logged-in-user"
    | _ -> click "#logout"
```
If the text in "#logged-in-user > a" is "Login" I expect it to click "#logged-in-user". I will need to add the actual logging in code, of course. If the user is already logged in, I want it to click "#logout" and logout.

Right now, I get a run-time error saying that it cannot find "#logout". It's trying to logout, when it's already logged in. I'm guessing there are multiple issues here.

**Comment by lefthandedgoat** [comment]
You are doing pattern matching on the string, and since "Login" is not the same as "#logged-in-user > a" it will always hit the last case of _
Then it is trying to click "#logout" which won't exist if the user is logged in.

There are a couple ways to solve this, both use ```someElement``` which will return an option type since the element may or may not exist.

One option is to change your matching to something like this
```
match (someElement "#logout") with
| Some(elem) -> click elem
| _ -> 
    "#username" << "Test"
    "#password" << "Password"
    click "Login"
```
Another option is to make a new helper function and use it
```
let exists selector =
    match (someElement selector) with
    | Some(_) -> true
    | _ -> false

if exists "#logout" then
    click "#logout"
else
    "#username" << "Test"
    "#password" << "Password"
    click "Login"
```

exists is a pretty useful helper function to have around so it may be the best route.

Hope this helps!

**Comment by Navmed** [comment]
Beautiful! You're awesome, thanks Chris!

**Comment by Navmed** [comment]
The match approach works, but the “if exists” throws a compile error:

Error    1    The value or constructor 'exists' is not defined

**Comment by lefthandedgoat** [comment]
make that the definition is above the place you are using it, or if its defined in another module that you have the 'open' statement at the top for that module
```
let exists selector = true

if exists "#something" then
    true
else
   false
```
That should compile no problem then you just need to fill in the bodies with the samples above.

**Comment by Navmed** [comment]
Ah! I should read more carefully. Thanks for pointing it out.

**Comment by lefthandedgoat** [comment]
Also make sure you are viewing code snippets via github. The email doesn't
maintain important formatting
