### ISSUE TITLE
Can't execute a simple example

### ISSUE THREAD

**Issue by vilinski** [lefthandedgoat/canopy#192]
Hi, strugglin with "Getting started" example with no luck in any browsers.
- ie, chrome: DriverServiceNotFoundException was unhandled - OpenQA.Selenium.DriverServiceNotFoundException' occurred in WebDriver.dll
Additional information: The file c:\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
- firefox: WebDriverException was unhandled - An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll
Additional information: Cannot find Firefox binary in PATH or default install locations. Make sure Firefox is installed. OS appears to be: OpenQA.Selenium.Platform

Schould be anything installed? Specific browser version? Anything missing in description?

**Comment by lefthandedgoat** [comment]
Yes you have to have firefox installed to use it.  To use Chrome you have to download chrome driver and put it in c:\

If you do not like putting it in c:\ you can put it somewhere else and change the path canopy use
```configuration.chromeDir <- "c:\your\path\"

Internet explorer also has a driver like chrome and you need to put it in c:\ or configure it.

We will update the getting started to make this more clear.

**Comment by vilinski** [comment]
Thank you!
I had already installed firefox, but x64 one in "C:\Program Files\Firefox\firefox.exe". Tried with latest 32 bit version - works. 
Also have downloaded latest chrome and IE drivers, both to local ".\drivers" directory. Like you described, added the path - works too. 

	let driversDir = """.\drivers"""
	configuration.chromeDir <- driversDir
	configuration.ieDir <- driversDir

Would it be a good idea to bootstrap download them to the local dir, like it does Paket?.
Now IE (version 11 installed) can open the page, but throws another exception at line `"#welcome" == "Welcome"`:

	OpenQA.Selenium.NoSuchWindowException was unhandled by user code 
	Message: An exception of type 'OpenQA.Selenium.NoSuchWindowException' occurred in
	WebDriver.dll but was not handled in user code
	Additional information: Unable to get browser

**Comment by lefthandedgoat** [comment]
I had the same problem with IE just now until I followed these instructions:

  * The IEDriverServer exectuable must be downloaded and placed in your PATH.
On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".
  * Additionally, "Enhanced Protected Mode" must be disabled for IE 10 and higher. This option is found in the Advanced tab of the Internet Options dialog.
The browser zoom level must be set to 100% so that the native mouse events can be set to the correct coordinates.
  * For IE 11 only, you will need to set a registry entry on the target computer so that the driver can maintain a connection to the instance of Internet Explorer it creates. For 32-bit Windows installations, the key you must examine in the registry editor is HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.

Found here: https://code.google.com/p/selenium/wiki/InternetExplorerDriver#Required_Configuration

**Comment by lefthandedgoat** [comment]
To answer your other question, I have thought about packaging the drivers, but they are 5-11 megs each and there are several, 3 OS + x64 and x86, so it would add a lot of size to the nuget package.

**Comment by vilinski** [comment]
I didn't mean nuget but rather fsx alike, wich just does download. But it is anyway useless, if the drivers require some more dancing with a tambourine.
Followed your instructions. Now IE works too! will go and try it out and make useful. Great thank :+1:

**Comment by lefthandedgoat** [comment]
You are welcome, enjoy!
