### ISSUE TITLE
Error using saveReportHtml

### ISSUE THREAD

**Issue by gkingston** [lefthandedgoat/canopy#194]
I may be doing it wrong, but I've tried various things to get saveReportHtml to work and have been unsuccessful so far.  I've done a try..with.. when using it and have also tried it with both chrome and firefox and the message is always either: 
`$ is not defined (UnexpectedJavaScriptError)` with firefox or 
`unknown error: $ is not defined with chrome`

I've tried various paths for the directory/filename including where the F# console app exe is at and still haven't ever gotten it to work.

Below is the top part of my code.  The tests work, but it always errors on the saveReportHtml.  I also saw a mention about needing a context so I added one before my tests.
```
open canopy
open runner
open types
open configuration
open reporters

start firefox
reporter <- new LiveHtmlReporter(Firefox) :> IReporter
let liveHtmlReporter = reporter :?> LiveHtmlReporter

try
    liveHtmlReporter.saveReportHtml @"C:\" "report"
with
    | :? (System.Exception) as ex -> printfn "%s" ex.Message

context "Tests"
//test code is below there
```

**Comment by lefthandedgoat** [comment]
```
reporter <- new LiveHtmlReporter(Chrome, configuration.chromeDir) :> IReporter
let liveHtmlReporter = reporter :?> LiveHtmlReporter
liveHtmlReporter.reportPath <- Some "reports/AutomationResults"

//define tests etc
run ()

quit()
```

The above works for me.  When quit is called it will save the report for you.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs#L211

That is the js that is run when it tries to run with it saves the report.  I bring that up because of your errors where it says that $ is not defined.  It makes me think its related to jquery.

If trying the above code doesnt work, can you check the dev console on the html report and see that there are no javascript errors?

**Comment by gkingston** [comment]
The above code you posted does work.  Not sure why calling saveReportHtml never worked(and would crash the browser if I didn't wrap it in try..with...), but just setting the reportPath works fine for me.
