### ISSUE TITLE
Stopping auto screen capture for failing tests

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#215]
Sometimes I want to stop the automatic screenshots after some tests fail. Is there a flag to disable these in the middle of test contest?

The scenario I'm using is installing a web site then performing some tests on it. If the installation process fails, I set a flag to fail fast and check this flag at the beginning of each tests and fail the test right away. So taking screen shots for all the tests is meaningless. Another useful feature to add is to allow skipping all tests without running them by setting a flag after a specific test fails.

**Comment by lefthandedgoat** [comment]
Ok I can work on these features

**Comment by lefthandedgoat** [comment]
Can you expand on this?

 Another useful feature to add is to allow skipping all tests without running them by setting a flag after a specific test fails.

Right now I have a flag called 'failFast' that will stop running any tests after any tests fails.

You would like an additional flag that is similar, but instead of not running more tests, it marks subsequent tests as skipped?

**Comment by galatrash-at-dnn** [comment]
Thanks Chris for following up and adding these features.

Yes, this is exactly what I meant: instead of me checking this in each subsequent test, this flag will be utilized by the canopy core and not the tests themselves. Also, there could be another flag for the context scope (skipping all subsequent tests in a context).

**Comment by lefthandedgoat** [comment]
I have the changes here: 

https://github.com/lefthandedgoat/canopy/commit/a5705ca997e2704d2969ed1191f857bae3050cfc

I reviewed them and I tested them.  If you want to review that would be great.  If things look right I will do a build.

**Comment by lefthandedgoat** [comment]
I dont know if messages are going back and forth correctly with email, because they are not showing up here, so I will put it here instead.

I looked at your diff, but do not know how to apply it, so I manually made similar changes.

You can review here: https://github.com/lefthandedgoat/canopy/commit/679cfd4f2c275bb4548922bf8b7acd23a2262033?diff=split

I dont have a team city instance setup locally to test the changes, but as long as `testIgnore` is the right TC keyword, it should work.

Let me know and I will do a nuget build.

**Comment by galatrash-at-dnn** [comment]
I received the emails but didn't find them in GitHub. I checked the diff view and you had all the changes. I think it is good to go - I've tested and seen these reported as ignored in TeamCity. Please create a nuget package for these.

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.36

Enjoy!

**Comment by galatrash-at-dnn** [comment]
Many thanks :)
