### ISSUE TITLE
Tagging captured images more clearly

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#224]
Hi Chris,

I'm having issues associating captured images to the failed tests when there are few failing ones. Is it possible to add some extra information to the captured images names? Maybe creating a random number and appending it to the time-stamp besides logging this in the reporter, or reporting the image file name in the log, or - even better - using the test name (after sanitizing) as the image file name.

**Comment by lefthandedgoat** [comment]
Let me see if I can think of a way to make it configurable so that people can adjust it to their liking.

I can make a configuration item that is a function that takes the all the information about a test, and returns a string.  The resulting string of the function would be the filename and people can implement it to have whatever custom filename they like.  It could default to current behavior.

Sound reasonable?

**Comment by galatrash-at-dnn** [comment]
Yes, this is okay as long as it doesn't break the existing feature and existing code if no override is used - I mean if the override function not used or it returns empty string (or null/None), then canopy defaults back to current behaviour of a time stamp file name.

**Comment by lefthandedgoat** [comment]
You can download here:

https://www.nuget.org/packages/canopy/0.9.42

You can see an example of a more robust file naming function.  It doesn't do a great job of cleaning the test names but is a reasonable enough example.  https://www.nuget.org/packages/canopy/0.9.42

Hope this solves your problem!

**Comment by galatrash-at-dnn** [comment]
It is working like charm :) Thanks for working so fast on it.

**Comment by lefthandedgoat** [comment]
Sure anytime!
