### ISSUE TITLE
Does Canopy have support for asynchronous behaviour?

### ISSUE THREAD

**Issue by jpierson** [lefthandedgoat/canopy#226]
Is support for testing asynchronous behaviour such a button that does an ajax request before affecting the DOM in any way that could be detectable through Selenium. From the snippet on the front page there is a check whether an element with an id of *button_clicked* has specific content after clicking the button.

```f#
    click "#button"
    "#button_clicked" == "button clicked"
```

My concern whether such test uses some type of polling or event listening pattern together with a timeout value to determine whether the assertion above passes or fails or if this is strictly just a synchronous test in this case. If this is a synchronous only test then are there any examples of an asynchronous one? It seems to me that the majority of tests I will expect to write with Canopy so I want to make sure that it is well supported before I start digging in. Please keep in mind that I'm quite new to F# and Selenium and most of my experience with web UI testing is with CodedUI.

**Comment by lefthandedgoat** [comment]
Most of the functions in canopy have built in reliability which is what I think you are after.  For example, if you were to click a save button, and it were to make an async call to the server, and when it was done show a messaged that said 'Saved', you could this

```
click "Save" //assuming the button has a innerHtml of 'Save'
displayed "Saved"
```
And even if the server takes a few seconds (up to 10, configurable) the test will still work.

A goal of canopy is to allow you write test in a natural way, and it tries to do everything it can make wait for something to come true (polling, checking IFrames for the condition, etc).

You won't find yourself explicitly sleeping often.

Hope this answers your question, if you have more let me know.

**Comment by jpierson** [comment]
Thanks @lefthandedgoat, this makes sense. I've been digging more into the Selenium documentation and and have come to understand that at least in JavaScript that there seems to be both an implicit and explicit way to wait between action and assertion. How much of the behaviour you describe above is specific to Canopy and how much of it is built into Selenium?

**Comment by lefthandedgoat** [comment]
Most of the things that canopy does, it does on its own.  As far as I know, Selenium has support for implicitly waiting for something to exist.

For example, if selenium you may do something like this:
```
driver.FindElement(By.Id("save")).click();
```
If there are no elements with id of save, it will fail.  With implicit waits on, it will try again for the element to exist, until a timeout.  I *think* though, that if the button is obstructed by a modal, selenium will try to click it once and fail.

In canopy, `click` will A) wait for something to exist, and B) try to click again and again until a timeout is reached.  If it failed because the element did not exist, the error message will state that.  If it fails because can't click it, it will tell you that in the error.

Same type of thing for assertions like equality.  It waits for the element to exist and it to have the value you expect.

Selenium works really well but its also picky, so you end up building retry logic, and canopy does most/all of that for you in a concise DSL.

**Comment by jpierson** [comment]
Nice explanation. Thanks for taking the time to share these important details.
