### ISSUE TITLE
Using Canopy to run PhantomJS on Mono ?

### ISSUE THREAD

**Issue by Thorium** [lefthandedgoat/canopy#228]
If I add NuGet reference to PhantomJS and then try to use Canopy on Mono like this:

        let path = Path.Combine(__SOURCE_DIRECTORY__, "..", "packages", "PhantomJS", "tools", "phantomjs")
        if Directory.Exists path then
           canopy.configuration.phantomJSDir <- path

        start phantomJS

Canopy will fail that packages/tools/phantomjs/phantomjs doesn't exist. Which is kind of correct as there is not the Linux/Mac executable in the Nuget package PhantomJS. There is only this exe and what I would like to try is to run my test with "mono phantomjs.exe". Is this possible or what would you recommend?

Can I do this somehow with Nuget package, or should I try to download the Linux/Mac executable with something like [this](https://gist.github.com/Thorium/91a481a819e904c5491b)?

**Comment by lefthandedgoat** [comment]
I use OSX and mono every day with chrome which requires a driver like phantom.  I can tell you how I do that and it will probably work wit phantom.

If it does not work with phantom I can tell you how I run chrome headless on Linux, which may work on OSX also.

In Progam.fs or early in your app
```
let executingDir = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)
canopy.configuration.chromeDir <- executingDir
```

We have the chromedriver for both windows, osx, and linux in a folder.  All of them have their extensions changed to .exe like : ```chromedriver_windows.exe, chromedriver_linux.exe, chromedriver_osx.exe```
All 3 files are set to copy on build.  We have a fake/rake task that after building will figure out what OS you are running on, and it will rename the right chromedriver_*.exe to just chromedriver.exe

This allows everything to work properly.

I have never used the nuget package, but the trick you have to do is get the phantom/chrome driver for osx or linux and put the .exe extension on it, because thats what the .Net version of selenium is looking for.

On linux you can run a fake X window with https://en.wikipedia.org/wiki/Xvfb and that worked.  I am not sure if there is a similar thing for OSX.  Again this is to run chromedriver headless, but if phantom works for you then thats fine too.

Hope this helps

**Comment by Thorium** [comment]
So is there a configuration in Canopy to tell running Chrome head-less?

**Comment by Thorium** [comment]
On Ubuntu and Win10.

**Comment by lefthandedgoat** [comment]
You can try these:

I had luck with xvfb in the past, using it to launch the .exe that controlled the tests.

https://gist.github.com/addyosmani/5336747

If the example does not work for windows, I have also had luck (4 years ago) with powershell remoting.  Here are some notes I send a friend.  This worked on windows 7.

```
You can either call this powershell stuff from rake prefixing each line with ps (I think) or create a script, and run that from rake

Start-Service winrm
#$nlm = [Activator]::CreateInstance([Type]::GetTypeFromCLSID([Guid]"{DCB00C01-570F-4A9B-8D69-199FDBA5723B}"))
#$connections = $nlm.getnetworkconnections()
#$connections |foreach {
#    if ($_.getnetwork().getcategory() -eq 0)
#    {
#        $_.getnetwork().setcategory(1)
#    }
#}
Enable-PSRemoting -force
set-item wsman:localhost\Shell\MaxMemoryPerShellMB 2048
icm -computer localhost { C:\projects\canopy\basictests\bin\Debug\basictests.exe }


the lines in the middle are comented with #.  You may need that uncommented if it complains about your network adapters being public?  Happened to me I think because of vmware network adapters.

Last line change it to be the path to your tests.

took like 6 hours to figure it out.  I had it figured out like hmm 1 hour into the whole thing but the 2nd to last line is what fixed it.  by default remote programs arent allowed to get over 150 megs.  PS was killing my firefox halfway though the test run.  Now it doesnt and it 'just works'

```

Hope this helps!  Please let me know if it does.  Also note that this is just a hack to make your tests run, but not pop up in your face and be annoying.
