### ISSUE TITLE
issue running sample code in VS 2015

### ISSUE THREAD

**Issue by shellwe** [lefthandedgoat/canopy#260]
I first ran into the issue about needing the chrome driver but I found out I needed to do that on here and got that resolved, it was running and going through the process and then I run into line 11 of wait.fs it and it is getting stuck on "innerwait timeout f"

It gives me this error

> 
> An exception of type 'OpenQA.Selenium.WebDriverTimeoutException' occurred in canopy.dll but was not handled in user code
> 
> Additional information: Timed out!
> 

I try to google that but get nothing.

**Comment by lefthandedgoat** [comment]
This is probably because of the way that canopy and selenium work.  Unfortunately they use exceptions for flow control.  When you run your code in Visual Studio it likes to stop on un-handled exceptions (the exceptions are actually handled but further up the stack.)

What I do is just run the resulting .exe from the console.  I generally create a Rake or Fake task and write code, then run the build/execute from command line.

You can also disable the behavior in VS, but its a generally useful one, and I think its not specific to projects, so it would effect your other projects =(

Here are some basic examples of both Rake (requires ruby) and Fake tasks to do what you want:

https://github.com/lefthandedgoat/canopy/blob/master/Rakefile.rb

https://github.com/lefthandedgoat/canopyStarterKit/blob/master/build.fsx

The second link is a different repository which may help you.  It has all the basic stuff to get started with canopy, including the chrome driver.  It has a good starting structure, and build tasks.  It also works on both Windows and OSX/Linux

**Comment by shellwe** [comment]
Thank you for the quick response! I am not a strong developer and have really never messed with testing but my boss wanted us to adopt Canopy so I am checking it out. We need something to log into our system and click on different pages to make sure they exist and none of them are broken as well as type some values into a form and run a test on the output for the numbers to be correct.

**Comment by lefthandedgoat** [comment]
Yes it should cover your needs for that!

The real trick to automation is getting good with css selectors and xpath selectors to help you find the right elements in the DOM so you can interact with them.

You can learn about jquery (special selectors that go beyond the power of css selectors) and css selectors here: 

https://oscarotero.com/jquery/

both are supported as well as xpath

**Comment by shellwe** [comment]
Excellent, thanks! I don't recall heearing of it as xpath before I watched the 5 minute Canopy video last week but I know selectors well enough, I'll take a look at the information there.
Thanks again!

**Comment by lefthandedgoat** [comment]
Xpath is different but it works also.  Xpath is a query language for XML documents and since HTML is basically an XML document, it works too.  Its more powerful but also much more ugly and painful to deal with, so I only use it for certain things like using `//div/../tr` where `..` will go up a level in the hierarchy.  You can't do that with css selectors currently

http://www.w3schools.com/xsl/xpath_syntax.asp

**Comment by shellwe** [comment]
Yea, that's the similar description you gave in your 5 minute video, that may be useful for some things I need to do. I just need it set up first and then I'll have some more questions, I am sure.
Thanks!

**Comment by shellwe** [comment]
FYI, I tried to build the starter kit and it produced a whole bunch of not defined errors on VS2015, That very well could just be something I am doing wrong. Hopefully I can just look through the code and piecemeal the parts I need together.

**Comment by lefthandedgoat** [comment]
Sorry I never put clear instructions on it.

After cloning run build.cmd from command line in the cloned directory and it will download all the nuget packages and run everything.  Then you can modify the code and add tests etc. and run again.

**Comment by shellwe** [comment]
Worked that time, thanks! In the past I always found that building pulls from nuget automatically. It would be good to have that on the download page, but honestly unless it was in bold bright text I probably wouldn't even have noticed.

**Comment by lefthandedgoat** [comment]
I just added it to the readme: https://github.com/lefthandedgoat/canopystarterkit

I've been doing everything from command line for a few years now and sometimes I forget to check building fresh from VS.

**Comment by shellwe** [comment]
Very pro-active of you! Now I just need to figure out how to implement this into our already massive site...

**Comment by lefthandedgoat** [comment]
Lol yes the site need some love.
