### ISSUE TITLE
Any plans to support Microsoft Edge browser?

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#264]
Are there any plans to add support for Microsoft Edge browser in the near future?

**Comment by lefthandedgoat** [comment]
I have to do some research on that.  I don't know how selenium and edge work together.  I will do that this afternoon and let you know.  Hopefully its as simple as an driver for edge.

**Comment by galatrash-at-dnn** [comment]
Here is where to obtain the web driver for Edge
https://www.microsoft.com/en-us/download/details.aspx?id=48212

**Comment by lefthandedgoat** [comment]
I have this 'working' on another branch, it has some issues:

There are actually 3 different 'Webdrivers' and the one you linked is the oldest one.  Read the last comment here: https://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/

To me that is a problem because google is not finding the right webdriver, and MS isn't doing a good job of representing them (good version numbers, listed out on a page with all downloads there).

~20% of the tests in my regression suit are failing.  Selenium Actions (drag/drop), some javascript functions, interacting with js alerts... none of these things seem to work.

I can get my test suite to run with debugger, or bash ??, but not from normal windows command prompt.  A browser is launch and it hangs there.

I honestly feel Edge isn't ready for prime time automation testing, but if you want I can add it.  I will call it EdgeBETA or EdgeUseAtOwnRisk or something to make it clear that it is not on the same level as other browser.

Thoughts?

**Comment by dnnautomation** [comment]
Sounds good to call it a beta support. At least those who want to test without these edgy issues can do some verification using this beta.

**Comment by galatrash-at-dnn** [comment]
Sounds good to call it a beta support. At least those who want to test without these edgy issues can do some verification using this beta.

**Comment by lefthandedgoat** [comment]
Added here, I will do a nuget build soon: https://github.com/lefthandedgoat/canopy/pull/265

just use 

`start edgeBETA`

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.54

Enjoy and good luck!

**Comment by galatrash-at-dnn** [comment]
I've tried the new code, but every time I call `start edgeBETA` I receive an error like this:
```
[10:31:33.704] - Listening on http://localhost:3904/
System.InvalidOperationException: Unknown error
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(String edgeDriverDirectory, EdgeOptions options)
   at canopy.core.start(BrowserStartMode b) in C:\Projects\canopy\src\canopy\canopy.fs:line 696
```

**Comment by lefthandedgoat** [comment]
Does it launch an instance of Edge?

**Comment by lefthandedgoat** [comment]
Also can you tell me what version of edge you have?  I have 25.105860.0

**Comment by galatrash-at-dnn** [comment]
It launches an instance and closes it right away. I have this version:
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

**Comment by lefthandedgoat** [comment]
Can you try the code in this blog post and see if it works for you?

https://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/

**Comment by galatrash-at-dnn** [comment]
It does the same thing and giving me the same error: `System.InvalidOperationException: Unknown error`

**Comment by lefthandedgoat** [comment]
Look in your C:\Program Files or C:\Program Files(x86) and see if there is a `Microsoft WebDriver` folder.  You can add that path to this line of code in the c# example

`driver = new EdgeDriver(@"C:\ADD\PATH\HERE");`

And see if that works.

Also maybe try to uninstall the drivers (add remove programs I think) and then install the Fall 2015 one.

Beyond that.. I dont know =( other than googling the error and seeing if something comes back.

**Comment by galatrash-at-dnn** [comment]
Thanks for your effort. I tried with all the versions of the driver and no matter what I did, the same error occurs. Googling didn't find anything. I may need to test on a different Windows 10 machine to see if it works. If it still not working, I will wait for a newer driver version o check.

**Comment by lefthandedgoat** [comment]
Ok sounds reasonable.  I have it 'working' in my VM, so if you ever need to compare version numbers etc, let me know.
