### ISSUE TITLE
Using Canopy to Test Email

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#272]
This one might be a stretch. My application allows a user to sign up for an account. We then generate a URL containing a time bombed token. The user must click on the link contained in the email that we sent out in a form letter before the token expires.

Question, How does one launch a tool like Outlook, search for an email, open it, and validate its contents using canopy?

**Comment by lefthandedgoat** [comment]
I dont think that you could.  You could maybe automate logging into gmail, or maybe outlook online.

It would probably be rather challenging, especially since you dont own the source for gmail, and it is likely it change without notice.

canopy is just an F# wrapper on Selenium so its main ability is to test web applications.

**Comment by sprice9161** [comment]
Okay....Thanks Chris....

**Comment by rmunn** [comment]
Canopy, as a library, might not be able to do this, but since your tests are written in F#, there's nothing stopping you from using other .Net code. If there's a C# interface for accessing Outlook programmatically, you could use that from F# as well.

I can't help you with the details of accessing Outlook, though, as I've never used Outlook and have no desire to start. I did find [this MSDN page](https://msdn.microsoft.com/en-us/library/ms268998.aspx), which looks like it's about Outlook plugins -- which brings up another idea. You could potentially write an Outlook plugin that looks for a certain subject line and From address, and writes the text content to a file. Then your F# Canopy tests look for that file to show up, read the confirmation URL out of it, and move on with the rest of the Web-based testing.

**Comment by NickLydon** [comment]
If you can set the host of the SMTP server, you can intercept the email in your test. I wrote a [simple library](https://github.com/NickLydon/SmtpInMemory) for my needs, but perhaps it might help you too. There might be other embeddable email servers in .NET too...

**Comment by JeremyBellows** [comment]
The solution to this depends on the variables of your situation.

What type of environment are tests being executed?
Are emails being sent in the environment?
Is it possible to output the time bombed token a different way for testing purposes?
Is testing email functionality vital at this stage of testing?

My recommendation is to generate the token link somehow via fsharp and manually navigate to it via canopy. 

The pseudo test would look like

```
sign up
generate url
navigate manually to url
Further assertions and validations
```

If it is impossible to generate the url via fsharp, then I would recommend investigating the possibility of transmitting the link some other way than SMTP for testing purposes. This should reduce complexity of tests considerably which increases long-term strategic value.

**Comment by amirrajan** [comment]
I think this ticket should be closed as not relevant to Canopy (possibly moved to Stack Overflow as a question instead)

**Comment by sprice9161** [comment]
Im using canopy, and asked for suggestions. Close it if you like but dont ask what this has to do with canopy. The question by definition is asking about canopy....

**Comment by lefthandedgoat** [comment]
You can also use the .net mail libraries to check the email and verify the contents of the body.

If you use pop3 it will download all the mails leaving nothing on the server.  Do this in the test setup, then you can call it again after the mail is sent, and there should be only one.
