### ISSUE TITLE
Download html

### ISSUE THREAD

**Issue by brains4math** [lefthandedgoat/canopy#279]
Is there a way to download html as string for analysis - seems like something very basic but I cannot find example in the documentation.

**Comment by lefthandedgoat** [comment]
Download the entire html of the page you are looking at?

If so this should work:

`let html = (js "return $('*').html();").ToString()`

this assumes you have jquery, due the $, if you don't you would have to figure out what the javascript to get the entire dom is.

**Comment by brains4math** [comment]
Thank you very much, that worked!

**Comment by brains4math** [comment]
Also, is there any way to download arbitrary (.txt .xls) files? I am getting "System.InvalidOperationException: unknown error: $ is not defined" assume is it because there is no javascript on the page ...

**Comment by lefthandedgoat** [comment]
Are you going to the page and its rending the .txt or .xls file for you? then you are trying to do the js trick above?

If thats the case, the rendering is some special browser specific thing probably so that trick won't work.

You would just need to write some code to do an http get and download the file to disk so you can open it and read it.  Check out http.fs https://github.com/relentless/Http.fs

**Comment by brains4math** [comment]
fwiw - I had some partial success with 
element "*" |> elementsWithin "*" |> List.map (fun x-> x.Text)

**Comment by lefthandedgoat** [comment]
If that works then it may be creating a webpage to reprsent the txt file and you can add jquery by running this script

```
            var jq = document.createElement('script');
            jq.src = '//code.jquery.com/jquery-2.2.1.min.js';
            document.getElementsByTagName('head')[0].appendChild(jq);
```

**Comment by lefthandedgoat** [comment]
You can also try a built in property that I just learned about:

browser.PageSource
