### ISSUE TITLE
The address isn’t valid

### ISSUE THREAD

**Issue by gmamais** [lefthandedgoat/canopy#291]
I tried to test canopy by following the steps of this page
https://lefthandedgoat.github.io/canopy/
but i failed.

When using firefox, I got the message from firefox

"The address isn’t valid"

Then I tried chrome but I got an exception 

OpenQA.Selenium.DriverServiceNotFoundException was unhandled
Message: An unhandled exception of type 'OpenQA.Selenium.DriverServiceNotFoundException' occurred in WebDriver.dll
Additional information: The file c:\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html

I tried edgeBETA or ie and I got the same exception.

What am I doing wrong ?

I am using Visual Studio 2015 (Community edition), windows 10

**Comment by lefthandedgoat** [comment]
Ah yes.  I chose to have the example use Firefox, because until recently, it did not require an additional driver .exe file.  Things have changed with Firefox, and Selenium 3, which accommodates those changes is not out of beta yet.

There are a couple choices.  You can downgrade your Firefox to v47 or lower, which will 'just work'.

If you want to use chrome or ie you need to download the `driver` and place it in root `C:\` (or you can change it via `canopy.configuration.chromeDir <- "c:\your\path"`

You can download the chrome driver (created by google) here: https://sites.google.com/a/chromium.org/chromedriver/downloads

Sorry for the hiccups, FF and Selenium are in a weird state.

**Comment by lefthandedgoat** [comment]
FF has an extended support release which should be safe to use: https://www.mozilla.org/en-US/firefox/organizations/

**Comment by gmamais** [comment]
Thank you very much.
Issue resolved.
