### ISSUE TITLE
phantomJs

### ISSUE THREAD

**Issue by fa10** [lefthandedgoat/canopy#308]
Hi,
I installed phantomJs to run the tests there, but when i enter a test and trying to use a `waitForElement` it is not working. 

```fs
    let executingDir () = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)

    configuration.phantomJSDir <- executingDir()
    start phantomJS
```

Anybody had some experience running phantonJS browser with canopy?

**Comment by lefthandedgoat** [comment]
I havent tried phantom in several years.   I will give it a shot in a bit and let you know.

**Comment by lefthandedgoat** [comment]
I spent some time on this and I can't reproduce the problem you are having.

```
"displayed test" &&&& fun _ ->
    !^ "http://lefthandedgoat.github.io/canopy/testpages/displayed"
    waitForElement "#displayed"
    displayed "#displayed"
```

```

"rightClicking Works" &&&& fun _ ->
    !^ "https://api.jquery.com/contextmenu/"
    let iframe = element "iframe"
    browser.SwitchTo().Frame(iframe) |> ignore
    notDisplayed ".contextmenu"

    rightClick "div:first"
    waitForElement ".contextmenu"
    displayed ".contextmenu"
```

Both of these work with phantom for me.

Can you help me reproduce the problem you are having?

**Comment by fa10** [comment]
Okay good to hear that it is working. Below i pasted my test and the code for it.
```cs
      "Homepage go to Search page"  &&&& fun _ ->
        PageObjects.HomePage.goToSearchPage "Málaga"
        on "Malaga-province/holiday-rentals"
```
The code that is used for this test looks like this.

```cs
module HomePage =    
    open canopy

    let goToSearchPage (search:string) = 
        waitForElement "#locationinputidforblink"
        "#locationinputidforblink" << search
        waitForElement ".tt-dataset-2"
        click (first "div.tt-dataset-2 span")
        click "#btnDoSearch"
```

Maybe you can show, how you setup the phantomJs in your main program?

**Comment by lefthandedgoat** [comment]
I did like you did, I just have the driver at `c:\` or some other place and set the configuration to point to that directory.

I don't see anything wrong with your code.  Does it work with Chrome but not Phantom?

**Comment by fa10** [comment]
Yes it does work with Chrome. Maybe i have the wrong version of Phantom installed which version do you have installed? Which nuget package are you using for Phantom ?

**Comment by fa10** [comment]
@lefthandedgoat is it possible that you are going to make a TFS runner? I need one for our build process.

**Comment by lefthandedgoat** [comment]
I use use the .exe found here http://phantomjs.org/download.html

Just drop it at `c:\`

If that doesn't work for you I can modify the canopyStarterKit to include phantom too so you can download something that works for me.

BTW, I never use phantom because I never found it to be much faster than Chrome.  The only real advantage it provided was being 'out of the way' because a browser didn't pop up.  Generally though, when you run tests locally you want to see them because you are just authoring them, improving their stability, or debugging them.  When run in your build process they don't bother you.   There are also hacks you can do using power shell remoting (not sure if they still work) to start chrome in a background process that you don't see.

For TFS, I haven't used it in years and I don't want to set it up to figure out how to make a thing for it.  For TeamCity there are specially formatted things you print to console to make it work, see here: https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs#L111

I used jenkins most recently I just ran it as a console application with a return code, if 0 tests failed, it passed the run, and if > 0 failed, the run was failed.  You can see how to do that here: https://github.com/lefthandedgoat/canopyStarterKit/blob/master/canopyStarterKit/Program.fs#L24

I used the html reporter and found a jenkins plugin that could save arbitrary artifacts of the build and save them.  The html report will save to a plain html file with embedded images and you can see how many failed by viewing it.

Another option would be to create a nunit reporter that creates an nunit compatible xml file that maybe tfs has a plugin for.  See a Junit one here: https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs#L384

Hope this helps.

**Comment by fa10** [comment]
@lefthandedgoat Thank you for your answers, i really appreciate it! 

I skipped the part with PhantomJs and just going to run it on Chrome in the build process. Still going to see if I can make it work. 

The TFS runner is something that i am working on now, and will let you know when I have a solution for it. Then if you want i can create a PR.

**Comment by lefthandedgoat** [comment]
Ok sounds good!

**Comment by fa10** [comment]
Hi,

I spent some time on getting the canopy tests result into the **TFS** build process. The solution i came up with is that i use your **JUnitRunner**. The steps is listed below:

- Setup JUnitRunner in your F# console application.
- Add Powershell script to your F# console application that executes the .exe that is generated.
- Add TFS build step that runs the powershell script.
- Add TFS build step "Publish Tests Results" (Select JUnit and add the path to your TestResults.xml)

**Comment by amirrajan** [comment]
Closed (chrome headless is the new hotness).
