### ISSUE TITLE
Text search whitespace

### ISSUE THREAD

**Issue by onionhammer** [lefthandedgoat/canopy#346]
Trying to click a button can lead to somewhat unpredictable behavior;

Example 1:
```html
<a>
    click here to proceed
</a>
```

Example 2
```html
<a>click here to proceed</a>
```

```f#
click (text "click here to proceed")
```

The above F# will error out for example 1, but work fine for example 2; I assume because of the whitespace around the text within the anchor tag.

**Comment by lefthandedgoat** [comment]
Yes this is a problem.

There are a few ways around it but first let me point out that you can do

`click "click here to proceed"`

instead of

`click (text "click here to proceed")`

The second one may be marginally faster if the website you are testing is VERY fast.  Use whichever is your preference =).

To get around it you can:

Have the website you are testing minimize the html, this will make html written as Example 1 one be sent to the client as Example 2

You can format your HTML like Example 2

You can add a finder like this

https://github.com/lefthandedgoat/canopy/blob/master/tests/basictests/Program.fs#L736-L742

Please note that you will need to write `click "click here to proceed"` for that to work.

This code should work but is untested.

```
let findByWhiteSpaceFriendlyText text f =
    try
        f(By.XPath(sprintf """.//*[normalize-space() = "%s"]""" text)) |> List.ofSeq
    with | _ -> []

addFinder findByWhiteSpaceFriendlyText 
```

Hope this helps.
