### ISSUE TITLE
Are sleeps avoidable in your experience?

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#396]
Are sleeps avoidable in your experience?

If you remember when it was unavoidable, please include some context.

Or...

Can you think of any context where sleep might be needed?

**Comment by lefthandedgoat** [comment]
Yes 99% avoidable.  The only time I use one is when I have tried and tried and can't figure it out.

Sleeps are bad because today 2 seconds is enough and tomorrow it isn't so you bump it to 4 seconds. 95% of the time no sleep or < 1 second would have been fine, but some times a longer sleep was needed.  Now you always pay the full price of the sleep even when it not necessary.

Use assertions like `displayed` or `==\equals` to make sure the page is in the right state before doing actions that sometimes fail.

Ex:  You login but sometimes its slow to take you to the home page.  Your test fails because it tries to go to a url after logging in.

go to login page
type in credentials
click login
go to some other page
(fails because login process did not complete correctly)

Change to:
go to login page
type in credentials
click login
`displayed "Hello Username` or `on "http://example.com/home"`
go to some other page
(fails because login process did not complete correctly)

That extra assertion that you are truly logged in before doing any further steps happen will help the stability of your tests a bunch.

All assertions in canopy have build in retry logic in there with a 500ms sleep, so it only wait as long as it needs to before moving forward, instead of a fixed sleep amount.

Hope this helps.
