### ISSUE TITLE
unable to Write text to element in chrome

### ISSUE THREAD

**Issue by manishdube** [lefthandedgoat/canopy#423]
using the << (write) action i am unable to write text to element in chrome. I am using  canopy 1.6.3 and this issue starting showing up only lately. earlier i was able to write text to an element.
I am able to read from the element, highlight the element etc.

not sure what changed.

**Comment by lefthandedgoat** [comment]
Can you see what version your chromedriver is?  When things stop working randomly its usually because your browser updated a version and your chromedriver doesn't support it anymore.

You can see what versions of chromedriver work with what versions of chrome here: https://sites.google.com/a/chromium.org/chromedriver/downloads

If that doesn't work let me know and we can dig further.

**Comment by manishdube** [comment]
updating the chromedriver to the latest solved the issue. Thank you very much. and thank you for the awesome DSL you created. absolutely love it!

**Comment by lefthandedgoat** [comment]
Awesome, glad that fixed it! Enjoy!
