### ISSUE TITLE
API Reference link is broken on home page

### ISSUE THREAD

**Issue by kevinmcfarlane** [lefthandedgoat/canopy#434]
[API Reference](https://lefthandedgoat.github.io/canopy/reference/index.html)

I assume it is somewhere?

**Comment by lefthandedgoat** [comment]
Its auto generated by the FSharp.Formatting library and when I updated to .net core I couldn't figure out how to get it to generate correctly.

I will spend a bit to try to figure it out.  If I can't I think I will just remove it because its not super useful, its just a bunch of type signatures.

Thanks for letting me know!

**Comment by JeremyBellows** [comment]
Fixed in #491 

https://lefthandedgoat.github.io/canopy//Api_Reference/canopy/canopy.html
