### ISSUE TITLE
selenium webdriver timeout exception

### ISSUE THREAD

**Issue by ankitgupta2k** [lefthandedgoat/canopy#466]
The selenium web driver has started happening and it happens instantly without waiting for it to timeout.
There is sequence of menu clicks as below in canopy test.
click "#Menu_1"
click "#Menu_1_SUB_MENU_1"
click "#Menu_1_SUB_MENU_1_SUB_MENU_2"

But the corresponding events doesn't happen and immediately timeout exception is throw with event on third level menu. Even when first two menu clicks didn't fire. And the timeout exception was immediate. 

 Below are the log details.
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 54465
OpenQA.Selenium.WebDriverTimeoutException: 'Timed out!'

**Comment by lefthandedgoat** [comment]
Is this a public site that I can look at?

If not try something like this:

```
displayed "#Menu_1"
click "#Menu_1"
displayed "#Menu_1_SUB_MENU_1"
click "#Menu_1_SUB_MENU_1"
displayed "#Menu_1_SUB_MENU_1_SUB_MENU_2"
click "#Menu_1_SUB_MENU_1_SUB_MENU_2"
```

Seems like its clicking the menus, and then trying to click the last one, but it can't because its not rendered.

Click only clicks, it doesnt click and make sure that whatever is supposed to happen after the click actually works.

**Comment by ankitgupta2k** [comment]
Thanks for the reply. It was an latency issue which was causing the sub menus to disappear and hence the immediate timeouts.
